version: "3"

services:
  ng_task:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./ng_task:/ng_task
    command: >
      sh -c "python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=ng_task
      - DB_USER=postgres
      - DB_PASS=testpass123
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=ng_task
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testpass123
