# Generated by Django 3.2.5 on 2021-07-17 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_car_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='car_id',
            new_name='car',
        ),
    ]
