# Generated by Django 3.2.5 on 2021-07-17 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_car_id_rating_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='car',
            new_name='car_id',
        ),
    ]
